import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-background text-foreground">
      <body className="font-sans min-h-screen bg-background text-foreground flex flex-col items-center" style={{ fontFamily: 'Inter, Arial, Helvetica, sans-serif' }}>
        <nav className="w-full flex justify-center py-8 mb-8 border-b border-neonPurple/30 sticky top-0 z-50 bg-background/90 backdrop-blur">
          <ul className="flex gap-10 text-lg font-semibold">
            <li><a href="/" className="hover:text-neonPurple transition">About</a></li>
            <li><a href="/skills" className="hover:text-neonBlue transition">Skills</a></li>
            <li><a href="/experience" className="hover:text-neonPurple transition">Experience</a></li>
            <li><a href="/projects" className="hover:text-neonBlue transition">Projects</a></li>
            <li><a href="/contact" className="hover:text-neonPurple transition">Contact</a></li>
          </ul>
        </nav>
        <main className="w-full max-w-4xl mx-auto px-6 flex-1 flex flex-col items-center justify-center">{children}</main>
      </body>
    </html>
  );
}
