import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`bg-background text-textPrimary min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex justify-between items-center px-8 py-6 border-b border-accentPurple/30">
          <div className="text-accentPurple font-bold text-2xl tracking-wide">Skyler Hall</div>
          <ul className="flex gap-8 text-lg">
            <li><a href="/" className="hover:text-accentBlue transition-colors">Home</a></li>
            <li><a href="/skills" className="hover:text-accentBlue transition-colors">Skills</a></li>
            <li><a href="/experience" className="hover:text-accentBlue transition-colors">Experience</a></li>
            <li><a href="/projects" className="hover:text-accentBlue transition-colors">Projects</a></li>
            <li><a href="/contact" className="hover:text-accentBlue transition-colors">Contact</a></li>
          </ul>
        </nav>
        <main className="max-w-4xl mx-auto px-4 py-8">
          {children}
        </main>
      </body>
    </html>
  );
}
